# Generated by Django 6.0.2 on 2026-02-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
